version: '3.8'

services:
  # MongoDB 서비스
  mongodb:
    image: mongo:4.4 # 개발시엔 latest 사용 배포시엔 4.4 사용
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./services/church-service/src/scripts/importChurchData.ts:/docker-entrypoint-initdb.d/importChurchData.ts:ro
    networks:
      - awana_network

  # 교회 서비스
  church-service:
    build:
      context: ./services/church-service
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - MONGODB_URI=mongodb://localhost:27017/church-service
      - PORT=3002
    depends_on:
      - mongodb
    networks:
      - awana_network

  # 이벤트 서비스
  event-service:
    build:
      context: ./services/event-service
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - MONGODB_URI=mongodb://localhost:27017/event-service
      - PORT=3001
    depends_on:
      - mongodb
    networks:
      - awana_network

  # 영수증 서비스
  receipt-service:
    build:
      context: ./services/receipt-service
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    environment:
      - MONGODB_URI=mongodb://localhost:27017/receipt-service
      - PORT=3003
    depends_on:
      - mongodb
    networks:
      - awana_network

networks:
  awana_network:
    driver: bridge

volumes:
  mongodb_data: 