version: '3.8'

services:
  event-service:
    build: .
    ports:
      - "3001:3001"
    environment:
      - MONGODB_URI=mongodb://localhost:27017/event-service
      - PORT=3001
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: 